[[constraint]]
    name = "k8s.io/apimachinery"
    version = "kubernetes-1.8.0"

[[constraint]]
    name = "k8s.io/apiserver"
    version = "kubernetes-1.8.0"

[[constraint]]
    name = "k8s.io/kubernetes"
    version = "v1.8.0"

[[constraint]]
    name = "github.com/golang/glog"
    branch = "master"

[[constraint]]
    name = "github.com/spf13/pflag"
    version = "v1.0.1"

[[constraint]]
    name = "gopkg.in/gcfg.v1"
    branch = "v1"

[prune]
    go-tests = true
    unused-packages = true