[[override]]
    name = "k8s.io/client-go"
    version = "kubernetes-1.10.2"

[[override]]
    name = "k8s.io/apiextensions-apiserver"
    version = "kubernetes-1.10.2"

[[override]]
    name = "github.com/docker/distribution"
    revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
    name = "k8s.io/apimachinery"
    version = "kubernetes-1.10.2"

[[constraint]]
    name = "k8s.io/apiserver"
    version = "kubernetes-1.10.2"

[[constraint]]
    name = "k8s.io/api"
    version = "kubernetes-1.10.2"

[[constraint]]
    name = "k8s.io/kubernetes"
    version = "v1.10.2"

[[constraint]]
    name = "github.com/golang/glog"
    branch = "master"

[[constraint]]
    name = "github.com/spf13/pflag"
    version = "v1.0.1"

[[constraint]]
    name = "gopkg.in/gcfg.v1"
    branch = "v1"

[prune]
    go-tests = true
    unused-packages = true